// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import ()

type User struct {
	ID       int32
	Name     string
	Lastname string
	Username string
	Email    string
	Password string
}
